### PR TITLE
remove current location because apple

### PR DESCRIPTION
**Pull request by chris-anderson67**

### CODE REVIEW

**Comment by chris-anderson67** [comment]
Apple wants us to tell the user WHY we are requesting their current location, but that functionality is apparently being released next week. So I'm removing it for now.

**Comment by chris-anderson67** [comment]
I thought it wouldn't but this PR is the build on the app store so idk what that "//" is doing but it isn't breaking it yet? 🤷‍♀️

**Comment by chris-anderson67** [comment]
I removed the line just to be safe

**Comment by bsteephenson** [comment]
Works locally. Im boggled. I don't get why it works but eh

**Pull request merged**
