### PR TITLE
The user should be prompted with our specific reason for needing location

### PR DESCRIPTION
**Pull request by bsteephenson**
"The app uses the user's location to provide an interactive tour experience." -- @bmfahey 

All this change does is
- sets the custom message
- sets showsUserLocation to true on the map

NOTE: It's not possible to test this change without running `exp build`, see https://docs.expo.io/versions/latest/guides/app-stores.html#system-permissions-dialogs-on-ios

Can you build and test this out? Also is the message okay?

### CODE REVIEW

**Comment by bsteephenson** [comment]
#142

**Comment by chris-anderson67** [comment]
The message looks perfect—it seems to work in my expo app but having trouble building the standalone app right now. I think as is it will crash on Android tho. Android usually needs an explicit permissions check at runtime.

**Comment by chris-anderson67** [comment]
@bsteephenson screen shot 2018-02-12 at 10 10 51 pm
The map works now—and the app doesn't crash or throw errors related to location. It also doesn't prompt the user for permission or display the current location. I think we might need to declare the permission in the android section of app.json.

**Comment by bsteephenson** [comment]
image
image

**Comment by bsteephenson** [comment]
Is it weird to ask for location permissions on app launch, or should we wait till you get to the explore page?

**Comment by chris-anderson67** [comment]
@bsteephenson It would probably be best to do it when the user goes to the explore page,  if that's possible.

**Pull request merged**
